apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: exam-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None   # headless — required for StatefulSet DNS
